#!/bin/env racket
#lang racket
(require racket/runtime-path)
(require yaml)
(define-runtime-path pkg-file "pkgs.yml")
(define-runtime-path dockerfile "Dockerfile")
(define-runtime-path dockerfile-header "Dockerfile.template")
(define data
  (with-input-from-file pkg-file
    (lambda ()
      (read-yaml))))

(define (zypper-in pkgs)
  (for ([(pkg idx) (in-indexed pkgs)])
    (when (equal? (modulo idx 10) 0)
      (when (> idx 0)
        (printf "\\\n"))
      (printf "    "))
    (printf "~a " pkg)))

(with-output-to-file
  dockerfile
  (lambda ()
    (display (port->string (open-input-file dockerfile-header)))
    (printf "RUN zypper --non-interactive in\\\n")
    (for ([(col idx) (in-indexed data)])
      (define name (hash-ref col "name"))
      (printf "    # For ~a\n" name)
      (define pkgs (hash-ref col "pkgs"))
      (zypper-in pkgs)
      (when (< idx (sub1 (length data)))
        (printf "\\"))
      (newline))
    (printf "RUN zypper clean -a\n"))
  #:exists 'replace)
